### ISSUE TITLE
Outdated ttf2woff dependency causing issues on OSX Catalina.

### ISSUE THREAD

**Issue by matyasf** [nfroidure/gulp-ttf2woff2#14]
The app uses `ttf2woff2` version 3.0.0, which uses `node-gyp` version 4.0.0. This version is a pain to use on newer OSXes because https://github.com/nodejs/node-gyp/issues/1927

Also its causing bugs in upstream packages, e.g. in `gulp-iconfont`

**Comment by pioug** [comment]
I pushed v4.0.0 (https://github.com/nfroidure/gulp-ttf2woff2/releases/tag/v4.0.0) that includes the latest version of `ttf2woff2`. So, it should use `node-gyp@7.1.2` now.

I'll see if I can update `gulp-iconfont` accordingly. Don't hesitate to create an issue there if I forget. Another maintainer may have a look too!

**Comment by matyasf** [comment]
Thanks for the quick fix! I'll open an issue with `gulp-iconfont` too
