### ISSUE TITLE
ttf2woff2 installation errors on travis

### ISSUE THREAD

**Issue by bmathews** [nfroidure/gulp-ttf2woff2#2]
I noticed npm install errors on travis on the project I'm working on. I noticed the errors are happening on the gulp-ttf2woff2 travis builds too. Is this known and/or not a concern? 

https://travis-ci.org/nfroidure/gulp-ttf2woff2#L98

```
> ttf2woff2@1.2.2 install /home/travis/build/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)
\mand line option ‘-std=c++11’
cc1plus: error: unrecognized command line option ‘-std=c++11’
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/travis/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
```

similar error? :
https://travis-ci.org/nfroidure/gulp-iconfont/builds/77682259#L93

**Comment by nfroidure** [comment]
The TravisCI containers doesn't embed a C++11 compiler per default so the compilation fails. This is not an issue sice there is a JS fallback.

The ttf2woff2 travis build has been set to compile it as expected, you can take a look at it if you're curious about how it is done.

That said, having it to sucessfully compile on your local setup would make it running faster.

**Comment by bmathews** [comment]
Perfect! Thanks for the thoughtful reply! :+1:
