### ISSUE TITLE
Windows: MSBuild error

### ISSUE THREAD

**Issue by GerjanOnline** [nfroidure/gulp-ttf2woff2#3]
My system:

<pre>
Windows 10 x64
Visual Studio 2015
Node v5.0.0
Npm v3.3.6
</pre>

I am trying to install `gulp-iconfont`

<pre>
npm install --save-dev gulp-iconfont
npm WARN engine ttf2woff2@2.0.1: wanted: {"node":">=4 <5"} (current: {"node":"5.0.0","npm":"3.3.6"})

> ttf2woff2@2.0.1 install D:\Gulp\vigetlabs-gulp-starter\node_modules\gulp-iconfont\node_modules\ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Gulp\vigetlabs-gulp-starter\node_modules\gulp-iconfont\node_modules\ttf2woff2
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> ttf2woff2@2.0.1 install D:\Gulp\vigetlabs-gulp-starter\node_modules\gulp-iconfont\node_modules\ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Gulp\vigetlabs-gulp-starter\node_modules\gulp-iconfont\node_modules\ttf2woff2
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
- gulp-svgicons2svgfont@2.3.1 node_modules\gulp-svgicons2svgfont
- gulp-ttf2woff2@1.1.2 node_modules\gulp-ttf2woff2
- nan@1.9.0 node_modules\nan
- node-gyp@2.0.2 node_modules\node-gyp
- graceful-fs@3.0.8 node_modules\node-gyp\node_modules\graceful-fs
- semver@4.3.6 node_modules\node-gyp\node_modules\semver
- plexer@0.0.3 node_modules\plexer
- readable-stream@1.1.13 node_modules\plexer\node_modules\readable-stream
- svgicons2svgfont@3.1.0 node_modules\svgicons2svgfont
- ttf2woff2@1.2.3 node_modules\ttf2woff2
gulp-starter@2.1.5 D:\Gulp\vigetlabs-gulp-starter
└─┬ gulp-iconfont@5.0.0
  ├─┬ gulp-svgicons2svgfont@2.4.0
  │ └── svgicons2svgfont@3.2.0
  ├─┬ gulp-ttf2woff2@2.0.0
  │ └─┬ ttf2woff2@2.0.1
  │   ├── nan@2.1.0
  │   └── node-gyp@3.0.3
  └── plexer@1.0.1
</pre>

**Comment by nfroidure** [comment]
Unfortunately, i can't test on windows and the build output your provided is not helpful in trying to understand why the build fails. The woff2 converter should still work since there is an emscripten fallback. Closing this issue since this is a ttf2woff2 issue.
