### ISSUE TITLE
Replace deprecated dependency gulp-util

### ISSUE THREAD

**Issue by florianbouvot** [nfroidure/gulp-ttf2woff2#5]
`gulp-util` has been recently deprecated.

Did you plan to replace this dependencies?

**Comment by nfroidure** [comment]
TBH, I no longer use icon fonts nor Gulp so there are no plans at all for this module until someone using it also wants to maintain it.

**Comment by florianbouvot** [comment]
@nfroidure thank you for your answer. I could not maintain it.
